// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cewijsesqsazxhfbfiur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNld2lqc2VzcXNhenhoZmJmaXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzY3MjIsImV4cCI6MjA2NjYxMjcyMn0.wGmB26YFgUwz5q0ijh-tf7pCtZ0kroTtHP5dz07X4Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);